// Generated by gencpp from file service_client/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SERVICE_CLIENT_MESSAGE_ADDTWOINTS_H
#define SERVICE_CLIENT_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <service_client/AddTwoIntsRequest.h>
#include <service_client/AddTwoIntsResponse.h>


namespace service_client
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace service_client


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service_client::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::service_client::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::service_client::AddTwoInts > {
  static const char* value()
  {
    return "service_client/AddTwoInts";
  }

  static const char* value(const ::service_client::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::service_client::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::service_client::AddTwoInts >
template<>
struct MD5Sum< ::service_client::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service_client::AddTwoInts >::value();
  }
  static const char* value(const ::service_client::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_client::AddTwoIntsRequest> should match
// service_traits::DataType< ::service_client::AddTwoInts >
template<>
struct DataType< ::service_client::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::service_client::AddTwoInts >::value();
  }
  static const char* value(const ::service_client::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service_client::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::service_client::AddTwoInts >
template<>
struct MD5Sum< ::service_client::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service_client::AddTwoInts >::value();
  }
  static const char* value(const ::service_client::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_client::AddTwoIntsResponse> should match
// service_traits::DataType< ::service_client::AddTwoInts >
template<>
struct DataType< ::service_client::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::service_client::AddTwoInts >::value();
  }
  static const char* value(const ::service_client::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_CLIENT_MESSAGE_ADDTWOINTS_H
