// Generated by gencpp from file service_client_server/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SERVICE_CLIENT_SERVER_MESSAGE_ADDTWOINTS_H
#define SERVICE_CLIENT_SERVER_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <service_client_server/AddTwoIntsRequest.h>
#include <service_client_server/AddTwoIntsResponse.h>


namespace service_client_server
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace service_client_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service_client_server::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::service_client_server::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::service_client_server::AddTwoInts > {
  static const char* value()
  {
    return "service_client_server/AddTwoInts";
  }

  static const char* value(const ::service_client_server::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::service_client_server::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::service_client_server::AddTwoInts >
template<>
struct MD5Sum< ::service_client_server::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service_client_server::AddTwoInts >::value();
  }
  static const char* value(const ::service_client_server::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_client_server::AddTwoIntsRequest> should match
// service_traits::DataType< ::service_client_server::AddTwoInts >
template<>
struct DataType< ::service_client_server::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::service_client_server::AddTwoInts >::value();
  }
  static const char* value(const ::service_client_server::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service_client_server::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::service_client_server::AddTwoInts >
template<>
struct MD5Sum< ::service_client_server::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service_client_server::AddTwoInts >::value();
  }
  static const char* value(const ::service_client_server::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_client_server::AddTwoIntsResponse> should match
// service_traits::DataType< ::service_client_server::AddTwoInts >
template<>
struct DataType< ::service_client_server::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::service_client_server::AddTwoInts >::value();
  }
  static const char* value(const ::service_client_server::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_CLIENT_SERVER_MESSAGE_ADDTWOINTS_H
